FROM golang:1.25-alpine AS dev

RUN apk add --no-cache git curl bash make net-tools iproute2

RUN addgroup -g 1001 appgroup && \
    adduser -D -s /bin/sh -u 1001 -G appgroup appuser

WORKDIR /app
RUN chown -R appuser:appgroup /app
USER appuser

COPY --chown=appuser:appgroup go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@latest

RUN mkdir -p /app/tmp

CMD ["air", "-c", "services/auth/air.toml"]
