app:
  name: "remaster"
  environment: "development"
  version: "1.0.0"

http:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"

grpc:
  port: "9090"
  host: "0.0.0.0"
  max_receive_size: 4194304  # 4MB
  max_send_size: 4194304     # 4MB
  connection_timeout: "5s"
  enable_reflection: true
  enable_health_check: true

mongo:
  uri: "mongodb://localhost:27017"
  database: "remaster"
  max_pool_size: 10
  min_pool_size: 2
  connect_timeout: "10s"
  server_selection_timeout: "5s"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 3
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"

jwt:
  secret_key: "secret"
  access_token_ttl: "15m"
  refresh_token_ttl: "24h"
  issuer: "remaster-auth"
  audience: "remaster-users"

oauth:
  google_client_id: "your-google-client-id"
  google_client_secret: "your-google-client-secret"
  google_redirect_url: "http://localhost:8080/auth/google/callback"

aws:
  region: "us-east-1"
  access_key_id: "your-aws-access-key"
  secret_access_key: "your-aws-secret-key"
  s3_bucket: "remaster-media"
  s3_region: "us-east-1"

kafka:
  brokers:
    - "localhost:9092"
  group_id: "remaster-consumer-group"
  auto_offset: "latest"
  session_timeout: "10s"
  retry_max: 3

log:
  level: "debug"
  format: "json"
  output: "stdout"
  file: ""