// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus int32

const (
	ResponseStatus_RESPONSE_STATUS_UNSPECIFIED       ResponseStatus = 0
	ResponseStatus_RESPONSE_STATUS_SUCCESS           ResponseStatus = 1
	ResponseStatus_RESPONSE_STATUS_ERROR             ResponseStatus = 2
	ResponseStatus_RESPONSE_STATUS_VALIDATION_ERROR  ResponseStatus = 3
	ResponseStatus_RESPONSE_STATUS_PERMISSION_DENIED ResponseStatus = 4
	ResponseStatus_RESPONSE_STATUS_NOT_FOUND         ResponseStatus = 5
	ResponseStatus_RESPONSE_STATUS_ALREADY_EXISTS    ResponseStatus = 6
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "RESPONSE_STATUS_UNSPECIFIED",
		1: "RESPONSE_STATUS_SUCCESS",
		2: "RESPONSE_STATUS_ERROR",
		3: "RESPONSE_STATUS_VALIDATION_ERROR",
		4: "RESPONSE_STATUS_PERMISSION_DENIED",
		5: "RESPONSE_STATUS_NOT_FOUND",
		6: "RESPONSE_STATUS_ALREADY_EXISTS",
	}
	ResponseStatus_value = map[string]int32{
		"RESPONSE_STATUS_UNSPECIFIED":       0,
		"RESPONSE_STATUS_SUCCESS":           1,
		"RESPONSE_STATUS_ERROR":             2,
		"RESPONSE_STATUS_VALIDATION_ERROR":  3,
		"RESPONSE_STATUS_PERMISSION_DENIED": 4,
		"RESPONSE_STATUS_NOT_FOUND":         5,
		"RESPONSE_STATUS_ALREADY_EXISTS":    6,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASC         SortOrder = 1
	SortOrder_SORT_ORDER_DESC        SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_IMAGE       MediaType = 1
	MediaType_MEDIA_TYPE_VIDEO       MediaType = 2
	MediaType_MEDIA_TYPE_DOCUMENT    MediaType = 3
	MediaType_MEDIA_TYPE_AUDIO       MediaType = 4
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_IMAGE",
		2: "MEDIA_TYPE_VIDEO",
		3: "MEDIA_TYPE_DOCUMENT",
		4: "MEDIA_TYPE_AUDIO",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_IMAGE":       1,
		"MEDIA_TYPE_VIDEO":       2,
		"MEDIA_TYPE_DOCUMENT":    3,
		"MEDIA_TYPE_AUDIO":       4,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type DayOfWeek int32

const (
	DayOfWeek_DAY_OF_WEEK_UNSPECIFIED DayOfWeek = 0
	DayOfWeek_DAY_OF_WEEK_MONDAY      DayOfWeek = 1
	DayOfWeek_DAY_OF_WEEK_TUESDAY     DayOfWeek = 2
	DayOfWeek_DAY_OF_WEEK_WEDNESDAY   DayOfWeek = 3
	DayOfWeek_DAY_OF_WEEK_THURSDAY    DayOfWeek = 4
	DayOfWeek_DAY_OF_WEEK_FRIDAY      DayOfWeek = 5
	DayOfWeek_DAY_OF_WEEK_SATURDAY    DayOfWeek = 6
	DayOfWeek_DAY_OF_WEEK_SUNDAY      DayOfWeek = 7
)

// Enum value maps for DayOfWeek.
var (
	DayOfWeek_name = map[int32]string{
		0: "DAY_OF_WEEK_UNSPECIFIED",
		1: "DAY_OF_WEEK_MONDAY",
		2: "DAY_OF_WEEK_TUESDAY",
		3: "DAY_OF_WEEK_WEDNESDAY",
		4: "DAY_OF_WEEK_THURSDAY",
		5: "DAY_OF_WEEK_FRIDAY",
		6: "DAY_OF_WEEK_SATURDAY",
		7: "DAY_OF_WEEK_SUNDAY",
	}
	DayOfWeek_value = map[string]int32{
		"DAY_OF_WEEK_UNSPECIFIED": 0,
		"DAY_OF_WEEK_MONDAY":      1,
		"DAY_OF_WEEK_TUESDAY":     2,
		"DAY_OF_WEEK_WEDNESDAY":   3,
		"DAY_OF_WEEK_THURSDAY":    4,
		"DAY_OF_WEEK_FRIDAY":      5,
		"DAY_OF_WEEK_SATURDAY":    6,
		"DAY_OF_WEEK_SUNDAY":      7,
	}
)

func (x DayOfWeek) Enum() *DayOfWeek {
	p := new(DayOfWeek)
	*p = x
	return p
}

func (x DayOfWeek) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DayOfWeek) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (DayOfWeek) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x DayOfWeek) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DayOfWeek.Descriptor instead.
func (DayOfWeek) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_INFO        NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_SUCCESS     NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_WARNING     NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_ERROR       NotificationType = 4
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_INFO",
		2: "NOTIFICATION_TYPE_SUCCESS",
		3: "NOTIFICATION_TYPE_WARNING",
		4: "NOTIFICATION_TYPE_ERROR",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED": 0,
		"NOTIFICATION_TYPE_INFO":        1,
		"NOTIFICATION_TYPE_SUCCESS":     2,
		"NOTIFICATION_TYPE_WARNING":     3,
		"NOTIFICATION_TYPE_ERROR":       4,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[4].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[4]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

type NotificationChannel int32

const (
	NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED NotificationChannel = 0
	NotificationChannel_NOTIFICATION_CHANNEL_EMAIL       NotificationChannel = 1
	NotificationChannel_NOTIFICATION_CHANNEL_SMS         NotificationChannel = 2
	NotificationChannel_NOTIFICATION_CHANNEL_PUSH        NotificationChannel = 3
	NotificationChannel_NOTIFICATION_CHANNEL_IN_APP      NotificationChannel = 4
)

// Enum value maps for NotificationChannel.
var (
	NotificationChannel_name = map[int32]string{
		0: "NOTIFICATION_CHANNEL_UNSPECIFIED",
		1: "NOTIFICATION_CHANNEL_EMAIL",
		2: "NOTIFICATION_CHANNEL_SMS",
		3: "NOTIFICATION_CHANNEL_PUSH",
		4: "NOTIFICATION_CHANNEL_IN_APP",
	}
	NotificationChannel_value = map[string]int32{
		"NOTIFICATION_CHANNEL_UNSPECIFIED": 0,
		"NOTIFICATION_CHANNEL_EMAIL":       1,
		"NOTIFICATION_CHANNEL_SMS":         2,
		"NOTIFICATION_CHANNEL_PUSH":        3,
		"NOTIFICATION_CHANNEL_IN_APP":      4,
	}
)

func (x NotificationChannel) Enum() *NotificationChannel {
	p := new(NotificationChannel)
	*p = x
	return p
}

func (x NotificationChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[5].Descriptor()
}

func (NotificationChannel) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[5]
}

func (x NotificationChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationChannel.Descriptor instead.
func (NotificationChannel) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

type SearchOperator int32

const (
	SearchOperator_SEARCH_OPERATOR_UNSPECIFIED           SearchOperator = 0
	SearchOperator_SEARCH_OPERATOR_EQUALS                SearchOperator = 1
	SearchOperator_SEARCH_OPERATOR_NOT_EQUALS            SearchOperator = 2
	SearchOperator_SEARCH_OPERATOR_CONTAINS              SearchOperator = 3
	SearchOperator_SEARCH_OPERATOR_NOT_CONTAINS          SearchOperator = 4
	SearchOperator_SEARCH_OPERATOR_STARTS_WITH           SearchOperator = 5
	SearchOperator_SEARCH_OPERATOR_ENDS_WITH             SearchOperator = 6
	SearchOperator_SEARCH_OPERATOR_GREATER_THAN          SearchOperator = 7
	SearchOperator_SEARCH_OPERATOR_LESS_THAN             SearchOperator = 8
	SearchOperator_SEARCH_OPERATOR_GREATER_THAN_OR_EQUAL SearchOperator = 9
	SearchOperator_SEARCH_OPERATOR_LESS_THAN_OR_EQUAL    SearchOperator = 10
	SearchOperator_SEARCH_OPERATOR_IN                    SearchOperator = 11
	SearchOperator_SEARCH_OPERATOR_NOT_IN                SearchOperator = 12
)

// Enum value maps for SearchOperator.
var (
	SearchOperator_name = map[int32]string{
		0:  "SEARCH_OPERATOR_UNSPECIFIED",
		1:  "SEARCH_OPERATOR_EQUALS",
		2:  "SEARCH_OPERATOR_NOT_EQUALS",
		3:  "SEARCH_OPERATOR_CONTAINS",
		4:  "SEARCH_OPERATOR_NOT_CONTAINS",
		5:  "SEARCH_OPERATOR_STARTS_WITH",
		6:  "SEARCH_OPERATOR_ENDS_WITH",
		7:  "SEARCH_OPERATOR_GREATER_THAN",
		8:  "SEARCH_OPERATOR_LESS_THAN",
		9:  "SEARCH_OPERATOR_GREATER_THAN_OR_EQUAL",
		10: "SEARCH_OPERATOR_LESS_THAN_OR_EQUAL",
		11: "SEARCH_OPERATOR_IN",
		12: "SEARCH_OPERATOR_NOT_IN",
	}
	SearchOperator_value = map[string]int32{
		"SEARCH_OPERATOR_UNSPECIFIED":           0,
		"SEARCH_OPERATOR_EQUALS":                1,
		"SEARCH_OPERATOR_NOT_EQUALS":            2,
		"SEARCH_OPERATOR_CONTAINS":              3,
		"SEARCH_OPERATOR_NOT_CONTAINS":          4,
		"SEARCH_OPERATOR_STARTS_WITH":           5,
		"SEARCH_OPERATOR_ENDS_WITH":             6,
		"SEARCH_OPERATOR_GREATER_THAN":          7,
		"SEARCH_OPERATOR_LESS_THAN":             8,
		"SEARCH_OPERATOR_GREATER_THAN_OR_EQUAL": 9,
		"SEARCH_OPERATOR_LESS_THAN_OR_EQUAL":    10,
		"SEARCH_OPERATOR_IN":                    11,
		"SEARCH_OPERATOR_NOT_IN":                12,
	}
)

func (x SearchOperator) Enum() *SearchOperator {
	p := new(SearchOperator)
	*p = x
	return p
}

func (x SearchOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[6].Descriptor()
}

func (SearchOperator) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[6]
}

func (x SearchOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchOperator.Descriptor instead.
func (SearchOperator) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ResponseStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=common.ResponseStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Errors        []*ErrorDetail         `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_RESPONSE_STATUS_UNSPECIFIED
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseResponse) GetErrors() []*ErrorDetail {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BaseResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                                  // Номер страницы (начиная с 1)
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`                             // Количество элементов на странице
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                                 // Поле для сортировки
	SortOrder     SortOrder              `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3,enum=common.SortOrder" json:"sort_order,omitempty"` // Направление сортировки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *PaginationRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *PaginationRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

type PaginationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalItems    int64                  `protobuf:"varint,4,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	HasPrev       bool                   `protobuf:"varint,6,opt,name=has_prev,json=hasPrev,proto3" json:"has_prev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResponse) Reset() {
	*x = PaginationResponse{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResponse) ProtoMessage() {}

func (x *PaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResponse.ProtoReflect.Descriptor instead.
func (*PaginationResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PaginationResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *PaginationResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PaginationResponse) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PaginationResponse) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *PaginationResponse) GetHasPrev() bool {
	if x != nil {
		return x.HasPrev
	}
	return false
}

type BaseFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedFrom   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_from,json=createdFrom,proto3" json:"created_from,omitempty"`
	CreatedTo     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_to,json=createdTo,proto3" json:"created_to,omitempty"`
	UpdatedFrom   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_from,json=updatedFrom,proto3" json:"updated_from,omitempty"`
	UpdatedTo     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_to,json=updatedTo,proto3" json:"updated_to,omitempty"`
	Status        []string               `protobuf:"bytes,5,rep,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseFilters) Reset() {
	*x = BaseFilters{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseFilters) ProtoMessage() {}

func (x *BaseFilters) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseFilters.ProtoReflect.Descriptor instead.
func (*BaseFilters) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *BaseFilters) GetCreatedFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedFrom
	}
	return nil
}

func (x *BaseFilters) GetCreatedTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTo
	}
	return nil
}

func (x *BaseFilters) GetUpdatedFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedFrom
	}
	return nil
}

func (x *BaseFilters) GetUpdatedTo() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedTo
	}
	return nil
}

func (x *BaseFilters) GetStatus() []string {
	if x != nil {
		return x.Status
	}
	return nil
}

type DateRangeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRangeFilter) Reset() {
	*x = DateRangeFilter{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRangeFilter) ProtoMessage() {}

func (x *DateRangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRangeFilter.ProtoReflect.Descriptor instead.
func (*DateRangeFilter) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *DateRangeFilter) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DateRangeFilter) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type NumericRangeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           *float64               `protobuf:"fixed64,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *float64               `protobuf:"fixed64,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericRangeFilter) Reset() {
	*x = NumericRangeFilter{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericRangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericRangeFilter) ProtoMessage() {}

func (x *NumericRangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericRangeFilter.ProtoReflect.Descriptor instead.
func (*NumericRangeFilter) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *NumericRangeFilter) GetMin() float64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *NumericRangeFilter) GetMax() float64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *Coordinates) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinates) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	HouseNumber   string                 `protobuf:"bytes,3,opt,name=house_number,json=houseNumber,proto3" json:"house_number,omitempty"`
	Apartment     string                 `protobuf:"bytes,4,opt,name=apartment,proto3" json:"apartment,omitempty"`
	Coordinates   *Coordinates           `protobuf:"bytes,5,opt,name=coordinates,proto3,oneof" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetHouseNumber() string {
	if x != nil {
		return x.HouseNumber
	}
	return ""
}

func (x *Address) GetApartment() string {
	if x != nil {
		return x.Apartment
	}
	return ""
}

func (x *Address) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	OriginalName  string                 `protobuf:"bytes,3,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Url           string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,7,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *FileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileInfo) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *FileInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileInfo) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *FileInfo) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

type ContactInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Telegram      string                 `protobuf:"bytes,3,opt,name=telegram,proto3" json:"telegram,omitempty"`
	Whatsapp      string                 `protobuf:"bytes,4,opt,name=whatsapp,proto3" json:"whatsapp,omitempty"`
	Website       string                 `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactInfo) Reset() {
	*x = ContactInfo{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfo) ProtoMessage() {}

func (x *ContactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfo.ProtoReflect.Descriptor instead.
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *ContactInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ContactInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactInfo) GetTelegram() string {
	if x != nil {
		return x.Telegram
	}
	return ""
}

func (x *ContactInfo) GetWhatsapp() string {
	if x != nil {
		return x.Whatsapp
	}
	return ""
}

func (x *ContactInfo) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

type Rating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Average       float64                `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Breakdown     *RatingBreakdown       `protobuf:"bytes,3,opt,name=breakdown,proto3" json:"breakdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rating) Reset() {
	*x = Rating{}
	mi := &file_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

func (x *Rating) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *Rating) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Rating) GetBreakdown() *RatingBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

type RatingBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stars_5       int32                  `protobuf:"varint,1,opt,name=stars_5,json=stars5,proto3" json:"stars_5,omitempty"`
	Stars_4       int32                  `protobuf:"varint,2,opt,name=stars_4,json=stars4,proto3" json:"stars_4,omitempty"`
	Stars_3       int32                  `protobuf:"varint,3,opt,name=stars_3,json=stars3,proto3" json:"stars_3,omitempty"`
	Stars_2       int32                  `protobuf:"varint,4,opt,name=stars_2,json=stars2,proto3" json:"stars_2,omitempty"`
	Stars_1       int32                  `protobuf:"varint,5,opt,name=stars_1,json=stars1,proto3" json:"stars_1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingBreakdown) Reset() {
	*x = RatingBreakdown{}
	mi := &file_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingBreakdown) ProtoMessage() {}

func (x *RatingBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingBreakdown.ProtoReflect.Descriptor instead.
func (*RatingBreakdown) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{12}
}

func (x *RatingBreakdown) GetStars_5() int32 {
	if x != nil {
		return x.Stars_5
	}
	return 0
}

func (x *RatingBreakdown) GetStars_4() int32 {
	if x != nil {
		return x.Stars_4
	}
	return 0
}

func (x *RatingBreakdown) GetStars_3() int32 {
	if x != nil {
		return x.Stars_3
	}
	return 0
}

func (x *RatingBreakdown) GetStars_2() int32 {
	if x != nil {
		return x.Stars_2
	}
	return 0
}

func (x *RatingBreakdown) GetStars_1() int32 {
	if x != nil {
		return x.Stars_1
	}
	return 0
}

type Statistics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders         int64                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	CompletedOrders     int64                  `protobuf:"varint,2,opt,name=completed_orders,json=completedOrders,proto3" json:"completed_orders,omitempty"`
	CancelledOrders     int64                  `protobuf:"varint,3,opt,name=cancelled_orders,json=cancelledOrders,proto3" json:"cancelled_orders,omitempty"`
	CompletionRate      float64                `protobuf:"fixed64,4,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	AverageResponseTime float64                `protobuf:"fixed64,5,opt,name=average_response_time,json=averageResponseTime,proto3" json:"average_response_time,omitempty"` // IN HOURS
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	mi := &file_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13}
}

func (x *Statistics) GetTotalOrders() int64 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *Statistics) GetCompletedOrders() int64 {
	if x != nil {
		return x.CompletedOrders
	}
	return 0
}

func (x *Statistics) GetCancelledOrders() int64 {
	if x != nil {
		return x.CancelledOrders
	}
	return 0
}

func (x *Statistics) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *Statistics) GetAverageResponseTime() float64 {
	if x != nil {
		return x.AverageResponseTime
	}
	return 0
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{14}
}

func (x *Money) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type PriceRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinPrice      *Money                 `protobuf:"bytes,1,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *Money                 `protobuf:"bytes,2,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "fixed", "range", "negotiable"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRange) Reset() {
	*x = PriceRange{}
	mi := &file_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRange) ProtoMessage() {}

func (x *PriceRange) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRange.ProtoReflect.Descriptor instead.
func (*PriceRange) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{15}
}

func (x *PriceRange) GetMinPrice() *Money {
	if x != nil {
		return x.MinPrice
	}
	return nil
}

func (x *PriceRange) GetMaxPrice() *Money {
	if x != nil {
		return x.MaxPrice
	}
	return nil
}

func (x *PriceRange) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type WorkingHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      []*DaySchedule         `protobuf:"bytes,1,rep,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkingHours) Reset() {
	*x = WorkingHours{}
	mi := &file_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkingHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkingHours) ProtoMessage() {}

func (x *WorkingHours) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkingHours.ProtoReflect.Descriptor instead.
func (*WorkingHours) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{16}
}

func (x *WorkingHours) GetSchedule() []*DaySchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type DaySchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           DayOfWeek              `protobuf:"varint,1,opt,name=day,proto3,enum=common.DayOfWeek" json:"day,omitempty"`
	TimeSlots     []*TimeSlot            `protobuf:"bytes,2,rep,name=time_slots,json=timeSlots,proto3" json:"time_slots,omitempty"`
	IsDayOff      bool                   `protobuf:"varint,3,opt,name=is_day_off,json=isDayOff,proto3" json:"is_day_off,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaySchedule) Reset() {
	*x = DaySchedule{}
	mi := &file_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaySchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaySchedule) ProtoMessage() {}

func (x *DaySchedule) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaySchedule.ProtoReflect.Descriptor instead.
func (*DaySchedule) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{17}
}

func (x *DaySchedule) GetDay() DayOfWeek {
	if x != nil {
		return x.Day
	}
	return DayOfWeek_DAY_OF_WEEK_UNSPECIFIED
}

func (x *DaySchedule) GetTimeSlots() []*TimeSlot {
	if x != nil {
		return x.TimeSlots
	}
	return nil
}

func (x *DaySchedule) GetIsDayOff() bool {
	if x != nil {
		return x.IsDayOff
	}
	return false
}

type TimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // HH:MM
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // HH:MM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_common_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{18}
}

func (x *TimeSlot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TimeSlot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Filters       []*SearchFilter        `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_common_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{19}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetFilters() []*SearchFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      SearchOperator         `protobuf:"varint,2,opt,name=operator,proto3,enum=common.SearchOperator" json:"operator,omitempty"`
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilter) Reset() {
	*x = SearchFilter{}
	mi := &file_common_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilter) ProtoMessage() {}

func (x *SearchFilter) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilter.ProtoReflect.Descriptor instead.
func (*SearchFilter) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{20}
}

func (x *SearchFilter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SearchFilter) GetOperator() SearchOperator {
	if x != nil {
		return x.Operator
	}
	return SearchOperator_SEARCH_OPERATOR_UNSPECIFIED
}

func (x *SearchFilter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type AuditLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ResourceType  string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IpAddress     string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,9,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEntry) Reset() {
	*x = AuditLogEntry{}
	mi := &file_common_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEntry) ProtoMessage() {}

func (x *AuditLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEntry.ProtoReflect.Descriptor instead.
func (*AuditLogEntry) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{21}
}

func (x *AuditLogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLogEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditLogEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLogEntry) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditLogEntry) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditLogEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AuditLogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditLogEntry) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditLogEntry) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n" +
	"\fBaseResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.common.ResponseStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x06errors\x18\x03 \x03(\v2\x13.common.ErrorDetailR\x06errors\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"Q\n" +
	"\vErrorDetail\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8d\x01\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x120\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x0e2\x11.common.SortOrderR\tsortOrder\"\xca\x01\n" +
	"\x12PaginationResponse\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\x1f\n" +
	"\vtotal_items\x18\x04 \x01(\x03R\n" +
	"totalItems\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\x12\x19\n" +
	"\bhas_prev\x18\x06 \x01(\bR\ahasPrev\"\x99\x02\n" +
	"\vBaseFilters\x12=\n" +
	"\fcreated_from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedFrom\x129\n" +
	"\n" +
	"created_to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedTo\x12=\n" +
	"\fupdated_from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vupdatedFrom\x129\n" +
	"\n" +
	"updated_to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedTo\x12\x16\n" +
	"\x06status\x18\x05 \x03(\tR\x06status\"m\n" +
	"\x0fDateRangeFilter\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"R\n" +
	"\x12NumericRangeFilter\x12\x15\n" +
	"\x03min\x18\x01 \x01(\x01H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x02 \x01(\x01H\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\"G\n" +
	"\vCoordinates\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"\xc2\x01\n" +
	"\aAddress\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12!\n" +
	"\fhouse_number\x18\x03 \x01(\tR\vhouseNumber\x12\x1c\n" +
	"\tapartment\x18\x04 \x01(\tR\tapartment\x12:\n" +
	"\vcoordinates\x18\x05 \x01(\v2\x13.common.CoordinatesH\x00R\vcoordinates\x88\x01\x01B\x0e\n" +
	"\f_coordinates\"\x80\x02\n" +
	"\bFileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12#\n" +
	"\roriginal_name\x18\x03 \x01(\tR\foriginalName\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12#\n" +
	"\rthumbnail_url\x18\a \x01(\tR\fthumbnailUrl\x12;\n" +
	"\vuploaded_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\"\x8b\x01\n" +
	"\vContactInfo\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\btelegram\x18\x03 \x01(\tR\btelegram\x12\x1a\n" +
	"\bwhatsapp\x18\x04 \x01(\tR\bwhatsapp\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsite\"o\n" +
	"\x06Rating\x12\x18\n" +
	"\aaverage\x18\x01 \x01(\x01R\aaverage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x125\n" +
	"\tbreakdown\x18\x03 \x01(\v2\x17.common.RatingBreakdownR\tbreakdown\"\x8e\x01\n" +
	"\x0fRatingBreakdown\x12\x17\n" +
	"\astars_5\x18\x01 \x01(\x05R\x06stars5\x12\x17\n" +
	"\astars_4\x18\x02 \x01(\x05R\x06stars4\x12\x17\n" +
	"\astars_3\x18\x03 \x01(\x05R\x06stars3\x12\x17\n" +
	"\astars_2\x18\x04 \x01(\x05R\x06stars2\x12\x17\n" +
	"\astars_1\x18\x05 \x01(\x05R\x06stars1\"\xe2\x01\n" +
	"\n" +
	"Statistics\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x03R\vtotalOrders\x12)\n" +
	"\x10completed_orders\x18\x02 \x01(\x03R\x0fcompletedOrders\x12)\n" +
	"\x10cancelled_orders\x18\x03 \x01(\x03R\x0fcancelledOrders\x12'\n" +
	"\x0fcompletion_rate\x18\x04 \x01(\x01R\x0ecompletionRate\x122\n" +
	"\x15average_response_time\x18\x05 \x01(\x01R\x13averageResponseTime\";\n" +
	"\x05Money\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\x9e\x01\n" +
	"\n" +
	"PriceRange\x12/\n" +
	"\tmin_price\x18\x01 \x01(\v2\r.common.MoneyH\x00R\bminPrice\x88\x01\x01\x12/\n" +
	"\tmax_price\x18\x02 \x01(\v2\r.common.MoneyH\x01R\bmaxPrice\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04typeB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_price\"?\n" +
	"\fWorkingHours\x12/\n" +
	"\bschedule\x18\x01 \x03(\v2\x13.common.DayScheduleR\bschedule\"\x81\x01\n" +
	"\vDaySchedule\x12#\n" +
	"\x03day\x18\x01 \x01(\x0e2\x11.common.DayOfWeekR\x03day\x12/\n" +
	"\n" +
	"time_slots\x18\x02 \x03(\v2\x10.common.TimeSlotR\ttimeSlots\x12\x1c\n" +
	"\n" +
	"is_day_off\x18\x03 \x01(\bR\bisDayOff\"D\n" +
	"\bTimeSlot\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\"\x90\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12.\n" +
	"\afilters\x18\x02 \x03(\v2\x14.common.SearchFilterR\afilters\x129\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"p\n" +
	"\fSearchFilter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x122\n" +
	"\boperator\x18\x02 \x01(\x0e2\x16.common.SearchOperatorR\boperator\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"\x8c\x03\n" +
	"\rAuditLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\tR\n" +
	"resourceId\x12?\n" +
	"\bmetadata\x18\x06 \x03(\v2#.common.AuditLogEntry.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\t \x01(\tR\tuserAgent\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xf9\x01\n" +
	"\x0eResponseStatus\x12\x1f\n" +
	"\x1bRESPONSE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RESPONSE_STATUS_SUCCESS\x10\x01\x12\x19\n" +
	"\x15RESPONSE_STATUS_ERROR\x10\x02\x12$\n" +
	" RESPONSE_STATUS_VALIDATION_ERROR\x10\x03\x12%\n" +
	"!RESPONSE_STATUS_PERMISSION_DENIED\x10\x04\x12\x1d\n" +
	"\x19RESPONSE_STATUS_NOT_FOUND\x10\x05\x12\"\n" +
	"\x1eRESPONSE_STATUS_ALREADY_EXISTS\x10\x06*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x02*\x82\x01\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_IMAGE\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_VIDEO\x10\x02\x12\x17\n" +
	"\x13MEDIA_TYPE_DOCUMENT\x10\x03\x12\x14\n" +
	"\x10MEDIA_TYPE_AUDIO\x10\x04*\xd8\x01\n" +
	"\tDayOfWeek\x12\x1b\n" +
	"\x17DAY_OF_WEEK_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DAY_OF_WEEK_MONDAY\x10\x01\x12\x17\n" +
	"\x13DAY_OF_WEEK_TUESDAY\x10\x02\x12\x19\n" +
	"\x15DAY_OF_WEEK_WEDNESDAY\x10\x03\x12\x18\n" +
	"\x14DAY_OF_WEEK_THURSDAY\x10\x04\x12\x16\n" +
	"\x12DAY_OF_WEEK_FRIDAY\x10\x05\x12\x18\n" +
	"\x14DAY_OF_WEEK_SATURDAY\x10\x06\x12\x16\n" +
	"\x12DAY_OF_WEEK_SUNDAY\x10\a*\xac\x01\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16NOTIFICATION_TYPE_INFO\x10\x01\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_SUCCESS\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_TYPE_WARNING\x10\x03\x12\x1b\n" +
	"\x17NOTIFICATION_TYPE_ERROR\x10\x04*\xb9\x01\n" +
	"\x13NotificationChannel\x12$\n" +
	" NOTIFICATION_CHANNEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNOTIFICATION_CHANNEL_EMAIL\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_CHANNEL_SMS\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_CHANNEL_PUSH\x10\x03\x12\x1f\n" +
	"\x1bNOTIFICATION_CHANNEL_IN_APP\x10\x04*\xb5\x03\n" +
	"\x0eSearchOperator\x12\x1f\n" +
	"\x1bSEARCH_OPERATOR_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SEARCH_OPERATOR_EQUALS\x10\x01\x12\x1e\n" +
	"\x1aSEARCH_OPERATOR_NOT_EQUALS\x10\x02\x12\x1c\n" +
	"\x18SEARCH_OPERATOR_CONTAINS\x10\x03\x12 \n" +
	"\x1cSEARCH_OPERATOR_NOT_CONTAINS\x10\x04\x12\x1f\n" +
	"\x1bSEARCH_OPERATOR_STARTS_WITH\x10\x05\x12\x1d\n" +
	"\x19SEARCH_OPERATOR_ENDS_WITH\x10\x06\x12 \n" +
	"\x1cSEARCH_OPERATOR_GREATER_THAN\x10\a\x12\x1d\n" +
	"\x19SEARCH_OPERATOR_LESS_THAN\x10\b\x12)\n" +
	"%SEARCH_OPERATOR_GREATER_THAN_OR_EQUAL\x10\t\x12&\n" +
	"\"SEARCH_OPERATOR_LESS_THAN_OR_EQUAL\x10\n" +
	"\x12\x16\n" +
	"\x12SEARCH_OPERATOR_IN\x10\v\x12\x1a\n" +
	"\x16SEARCH_OPERATOR_NOT_IN\x10\fB\x1eZ\x1cremaster/shared/proto/commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_common_proto_goTypes = []any{
	(ResponseStatus)(0),           // 0: common.ResponseStatus
	(SortOrder)(0),                // 1: common.SortOrder
	(MediaType)(0),                // 2: common.MediaType
	(DayOfWeek)(0),                // 3: common.DayOfWeek
	(NotificationType)(0),         // 4: common.NotificationType
	(NotificationChannel)(0),      // 5: common.NotificationChannel
	(SearchOperator)(0),           // 6: common.SearchOperator
	(*BaseResponse)(nil),          // 7: common.BaseResponse
	(*ErrorDetail)(nil),           // 8: common.ErrorDetail
	(*PaginationRequest)(nil),     // 9: common.PaginationRequest
	(*PaginationResponse)(nil),    // 10: common.PaginationResponse
	(*BaseFilters)(nil),           // 11: common.BaseFilters
	(*DateRangeFilter)(nil),       // 12: common.DateRangeFilter
	(*NumericRangeFilter)(nil),    // 13: common.NumericRangeFilter
	(*Coordinates)(nil),           // 14: common.Coordinates
	(*Address)(nil),               // 15: common.Address
	(*FileInfo)(nil),              // 16: common.FileInfo
	(*ContactInfo)(nil),           // 17: common.ContactInfo
	(*Rating)(nil),                // 18: common.Rating
	(*RatingBreakdown)(nil),       // 19: common.RatingBreakdown
	(*Statistics)(nil),            // 20: common.Statistics
	(*Money)(nil),                 // 21: common.Money
	(*PriceRange)(nil),            // 22: common.PriceRange
	(*WorkingHours)(nil),          // 23: common.WorkingHours
	(*DaySchedule)(nil),           // 24: common.DaySchedule
	(*TimeSlot)(nil),              // 25: common.TimeSlot
	(*SearchRequest)(nil),         // 26: common.SearchRequest
	(*SearchFilter)(nil),          // 27: common.SearchFilter
	(*AuditLogEntry)(nil),         // 28: common.AuditLogEntry
	nil,                           // 29: common.AuditLogEntry.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	0,  // 0: common.BaseResponse.status:type_name -> common.ResponseStatus
	8,  // 1: common.BaseResponse.errors:type_name -> common.ErrorDetail
	30, // 2: common.BaseResponse.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 3: common.PaginationRequest.sort_order:type_name -> common.SortOrder
	30, // 4: common.BaseFilters.created_from:type_name -> google.protobuf.Timestamp
	30, // 5: common.BaseFilters.created_to:type_name -> google.protobuf.Timestamp
	30, // 6: common.BaseFilters.updated_from:type_name -> google.protobuf.Timestamp
	30, // 7: common.BaseFilters.updated_to:type_name -> google.protobuf.Timestamp
	30, // 8: common.DateRangeFilter.from:type_name -> google.protobuf.Timestamp
	30, // 9: common.DateRangeFilter.to:type_name -> google.protobuf.Timestamp
	14, // 10: common.Address.coordinates:type_name -> common.Coordinates
	30, // 11: common.FileInfo.uploaded_at:type_name -> google.protobuf.Timestamp
	19, // 12: common.Rating.breakdown:type_name -> common.RatingBreakdown
	21, // 13: common.PriceRange.min_price:type_name -> common.Money
	21, // 14: common.PriceRange.max_price:type_name -> common.Money
	24, // 15: common.WorkingHours.schedule:type_name -> common.DaySchedule
	3,  // 16: common.DaySchedule.day:type_name -> common.DayOfWeek
	25, // 17: common.DaySchedule.time_slots:type_name -> common.TimeSlot
	27, // 18: common.SearchRequest.filters:type_name -> common.SearchFilter
	9,  // 19: common.SearchRequest.pagination:type_name -> common.PaginationRequest
	6,  // 20: common.SearchFilter.operator:type_name -> common.SearchOperator
	29, // 21: common.AuditLogEntry.metadata:type_name -> common.AuditLogEntry.MetadataEntry
	30, // 22: common.AuditLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[6].OneofWrappers = []any{}
	file_common_proto_msgTypes[8].OneofWrappers = []any{}
	file_common_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
